
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN}
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ".:/app"
